# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='host_to_remote_users',
            field=models.ManyToManyField(blank=True, null=True, to='web.HostToRemoteUser'),
        ),
    ]
