# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_host_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttoremoteuser',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
