# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_hosttoremoteuser_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='system_type',
            field=models.CharField(choices=[('0', 'Windows'), ('1', 'Linux/Unix')], default='linux', max_length=32),
        ),
    ]
